apiVersion: v1
kind: Service
metadata:
  labels:
    app: daps
  name: daps
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: daps

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: daps
  name: daps
  namespace: example-ds
spec:
  replicas: 1
  selector:
    matchLabels:
      app: daps
  template:
    metadata:
      labels:
        app: daps
    spec:
      containers:
        - image: "karikolehmainen/dsil-daps:0.1"
          imagePullPolicy: Always
          name: daps
          ports:
          - containerPort: 80
            name: http
